[package]
name = "allwright-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lightweight allwright engine core with shared client and transport APIs."
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["automation", "testing", "browser", "grpc", "bidi"]
categories = ["development-tools::testing", "command-line-utilities", "api-bindings"]

[lib]
name = "allwright"

[features]
default = ["client"]
client = []
server = []

[dependencies]
allwright-plugin-sdk = { path = "../allwright-plugin-sdk", version = "0.0.55" }
allwright-surface-mobile = { path = "../allwright-surface-mobile", version = "0.0.55" }
flate2 = { workspace = true }
libloading = { workspace = true }
prost = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tokio-stream = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
