// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PingRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PingResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CommandRetryOptions {
    #[prost(uint32, optional, tag = "1")]
    pub timeout_ms: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub retry_interval_ms: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectMobileCommand {
    #[prost(enumeration = "MobilePlatform", tag = "1")]
    pub platform: i32,
    #[prost(string, optional, tag = "2")]
    pub device: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub adb_endpoint: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub preserve_app_state: bool,
    #[prost(message, optional, tag = "5")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MobileConnectedEvent {
    #[prost(enumeration = "MobilePlatform", tag = "1")]
    pub platform: i32,
    #[prost(string, tag = "2")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(enumeration = "DeviceConnectionKind", tag = "5")]
    pub connection_kind: i32,
    #[prost(string, tag = "6")]
    pub backend: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub device_session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub initial_app_session_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "9")]
    pub package_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub activity_name: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LaunchAppCommand {
    #[prost(string, optional, tag = "1")]
    pub apk_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub app_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub launch_activity: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "4")]
    pub stop_before_launch: bool,
    #[prost(message, optional, tag = "5")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppLaunchedEvent {
    #[prost(string, tag = "1")]
    pub app_session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub package_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub activity_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub webview_context: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MobilePlatform {
    Unspecified = 0,
    Android = 1,
    Ios = 2,
}
impl MobilePlatform {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MOBILE_PLATFORM_UNSPECIFIED",
            Self::Android => "MOBILE_PLATFORM_ANDROID",
            Self::Ios => "MOBILE_PLATFORM_IOS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOBILE_PLATFORM_UNSPECIFIED" => Some(Self::Unspecified),
            "MOBILE_PLATFORM_ANDROID" => Some(Self::Android),
            "MOBILE_PLATFORM_IOS" => Some(Self::Ios),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeviceConnectionKind {
    Unspecified = 0,
    Usb = 1,
    Emulator = 2,
    RemoteAdb = 3,
}
impl DeviceConnectionKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DEVICE_CONNECTION_KIND_UNSPECIFIED",
            Self::Usb => "DEVICE_CONNECTION_KIND_USB",
            Self::Emulator => "DEVICE_CONNECTION_KIND_EMULATOR",
            Self::RemoteAdb => "DEVICE_CONNECTION_KIND_REMOTE_ADB",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEVICE_CONNECTION_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "DEVICE_CONNECTION_KIND_USB" => Some(Self::Usb),
            "DEVICE_CONNECTION_KIND_EMULATOR" => Some(Self::Emulator),
            "DEVICE_CONNECTION_KIND_REMOTE_ADB" => Some(Self::RemoteAdb),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LaunchBrowserCommand {
    #[prost(enumeration = "BrowserKind", tag = "1")]
    pub browser_kind: i32,
    #[prost(string, optional, tag = "2")]
    pub browser_binary: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BrowserLaunchedEvent {
    #[prost(enumeration = "BrowserKind", tag = "1")]
    pub browser_kind: i32,
    #[prost(string, tag = "2")]
    pub browser: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub user_data_dir: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub initial_page_session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LaunchChromeCommand {
    #[prost(string, optional, tag = "1")]
    pub chrome_binary: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChromeLaunchedEvent {
    #[prost(string, tag = "1")]
    pub browser: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cdp_websocket_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub user_data_dir: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub initial_page_session_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BrowserKind {
    Unspecified = 0,
    Chromium = 1,
    Firefox = 2,
}
impl BrowserKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BROWSER_KIND_UNSPECIFIED",
            Self::Chromium => "BROWSER_KIND_CHROMIUM",
            Self::Firefox => "BROWSER_KIND_FIREFOX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BROWSER_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "BROWSER_KIND_CHROMIUM" => Some(Self::Chromium),
            "BROWSER_KIND_FIREFOX" => Some(Self::Firefox),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SurfaceSessionCommand {
    #[prost(oneof = "surface_session_command::Command", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub command: ::core::option::Option<surface_session_command::Command>,
}
/// Nested message and enum types in `SurfaceSessionCommand`.
pub mod surface_session_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "1")]
        LaunchChrome(super::LaunchChromeCommand),
        #[prost(message, tag = "2")]
        OpenContext(super::OpenContextCommand),
        #[prost(message, tag = "3")]
        Ping(super::SessionPingCommand),
        #[prost(message, tag = "4")]
        Close(super::CloseSurfaceSessionCommand),
        #[prost(message, tag = "5")]
        LaunchBrowser(super::LaunchBrowserCommand),
        #[prost(message, tag = "6")]
        ConnectMobile(super::ConnectMobileCommand),
        #[prost(message, tag = "7")]
        LaunchApp(super::LaunchAppCommand),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenContextCommand {
    #[prost(message, optional, tag = "1")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionPingCommand {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseSurfaceSessionCommand {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SurfaceSessionEvent {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(oneof = "surface_session_event::Event", tags = "2, 3, 4, 5, 6, 7, 8, 9")]
    pub event: ::core::option::Option<surface_session_event::Event>,
}
/// Nested message and enum types in `SurfaceSessionEvent`.
pub mod surface_session_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        ChromeLaunched(super::ChromeLaunchedEvent),
        #[prost(message, tag = "3")]
        ContextOpened(super::ContextOpenedEvent),
        #[prost(message, tag = "4")]
        Pong(super::SessionPongEvent),
        #[prost(message, tag = "5")]
        Closed(super::SurfaceSessionClosedEvent),
        #[prost(message, tag = "6")]
        Error(super::SurfaceSessionErrorEvent),
        #[prost(message, tag = "7")]
        BrowserLaunched(super::BrowserLaunchedEvent),
        #[prost(message, tag = "8")]
        MobileConnected(super::MobileConnectedEvent),
        #[prost(message, tag = "9")]
        AppLaunched(super::AppLaunchedEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextOpenedEvent {
    #[prost(string, tag = "1")]
    pub context_session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionPongEvent {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SurfaceSessionClosedEvent {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SurfaceSessionErrorEvent {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionCommand {
    #[prost(string, tag = "1")]
    pub surface_session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub context_session_id: ::prost::alloc::string::String,
    #[prost(
        oneof = "context_session_command::Command",
        tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16"
    )]
    pub command: ::core::option::Option<context_session_command::Command>,
}
/// Nested message and enum types in `ContextSessionCommand`.
pub mod context_session_command {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag = "3")]
        Ping(super::ContextSessionPingCommand),
        #[prost(message, tag = "4")]
        Close(super::CloseContextSessionCommand),
        #[prost(message, tag = "5")]
        Navigate(super::NavigatePageCommand),
        #[prost(message, tag = "6")]
        ClickElement(super::ClickElementCommand),
        #[prost(message, tag = "7")]
        CountElements(super::CountElementsCommand),
        #[prost(message, tag = "8")]
        HighlightElements(super::HighlightElementsCommand),
        #[prost(message, tag = "9")]
        FocusElement(super::FocusElementCommand),
        #[prost(message, tag = "10")]
        FillElement(super::FillElementCommand),
        #[prost(message, tag = "11")]
        HoverElement(super::HoverElementCommand),
        #[prost(message, tag = "12")]
        PressKey(super::PressKeyCommand),
        #[prost(message, tag = "13")]
        GetTextContent(super::GetTextContentCommand),
        #[prost(message, tag = "14")]
        GetInnerText(super::GetInnerTextCommand),
        #[prost(message, tag = "15")]
        WaitForSelector(super::WaitForSelectorCommand),
        #[prost(message, tag = "16")]
        Screenshot(super::ScreenshotCommand),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionPingCommand {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CloseContextSessionCommand {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionEvent {
    #[prost(string, tag = "1")]
    pub context_session_id: ::prost::alloc::string::String,
    #[prost(
        oneof = "context_session_event::Event",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18"
    )]
    pub event: ::core::option::Option<context_session_event::Event>,
}
/// Nested message and enum types in `ContextSessionEvent`.
pub mod context_session_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        Attached(super::ContextSessionAttachedEvent),
        #[prost(message, tag = "3")]
        Pong(super::ContextSessionPongEvent),
        #[prost(message, tag = "4")]
        Closed(super::ContextSessionClosedEvent),
        #[prost(message, tag = "5")]
        Error(super::ContextSessionErrorEvent),
        #[prost(message, tag = "6")]
        Navigated(super::PageNavigatedEvent),
        #[prost(message, tag = "7")]
        ChromiumBidiInjection(super::ChromiumBidiInjectionEvent),
        #[prost(message, tag = "8")]
        ElementClicked(super::ElementClickedEvent),
        #[prost(message, tag = "9")]
        ElementCounted(super::ElementCountedEvent),
        #[prost(message, tag = "10")]
        ElementsHighlighted(super::ElementsHighlightedEvent),
        #[prost(message, tag = "11")]
        ElementFocused(super::ElementFocusedEvent),
        #[prost(message, tag = "12")]
        ElementFilled(super::ElementFilledEvent),
        #[prost(message, tag = "13")]
        ElementHovered(super::ElementHoveredEvent),
        #[prost(message, tag = "14")]
        KeyPressed(super::KeyPressedEvent),
        #[prost(message, tag = "15")]
        TextContentResolved(super::TextContentResolvedEvent),
        #[prost(message, tag = "16")]
        InnerTextResolved(super::InnerTextResolvedEvent),
        #[prost(message, tag = "17")]
        SelectorWaitSatisfied(super::SelectorWaitSatisfiedEvent),
        #[prost(message, tag = "18")]
        ScreenshotCaptured(super::ScreenshotCapturedEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionAttachedEvent {
    #[prost(string, tag = "1")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionPongEvent {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionClosedEvent {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContextSessionErrorEvent {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NavigatePageCommand {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClickElementCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CountElementsCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HighlightElementsCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "2")]
    pub duration_ms: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "3")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FocusElementCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FillElementCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HoverElementCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PressKeyCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub text: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTextContentCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInnerTextCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WaitForSelectorCommand {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "2")]
    pub visible: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "3")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ScreenshotCommand {
    #[prost(message, optional, tag = "1")]
    pub retry_options: ::core::option::Option<CommandRetryOptions>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PageNavigatedEvent {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChromiumBidiInjectionEvent {
    #[prost(string, tag = "1")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub bidi_session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mapper_target_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub mapper_session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub package_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementClickedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub bidi_session_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementCountedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub count: u32,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementsHighlightedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub count: u32,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementFocusedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementFilledEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElementHoveredEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyPressedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextContentResolvedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InnerTextResolvedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectorWaitSatisfiedEvent {
    #[prost(string, tag = "1")]
    pub css_selector: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub visible: bool,
    #[prost(string, tag = "3")]
    pub note: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenshotCapturedEvent {
    #[prost(bytes = "vec", tag = "1")]
    pub png_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub note: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod engine_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct EngineServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl EngineServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> EngineServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> EngineServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            EngineServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn ping(
            &mut self,
            request: impl tonic::IntoRequest<super::PingRequest>,
        ) -> std::result::Result<tonic::Response<super::PingResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/allwright.engine.v1.EngineService/Ping",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("allwright.engine.v1.EngineService", "Ping"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn surface_session(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::SurfaceSessionCommand,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SurfaceSessionEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/allwright.engine.v1.EngineService/SurfaceSession",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "allwright.engine.v1.EngineService",
                        "SurfaceSession",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        pub async fn context_session(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::ContextSessionCommand,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ContextSessionEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/allwright.engine.v1.EngineService/ContextSession",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "allwright.engine.v1.EngineService",
                        "ContextSession",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod engine_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EngineServiceServer.
    #[async_trait]
    pub trait EngineService: std::marker::Send + std::marker::Sync + 'static {
        async fn ping(
            &self,
            request: tonic::Request<super::PingRequest>,
        ) -> std::result::Result<tonic::Response<super::PingResponse>, tonic::Status>;
        /// Server streaming response type for the SurfaceSession method.
        type SurfaceSessionStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::SurfaceSessionEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn surface_session(
            &self,
            request: tonic::Request<tonic::Streaming<super::SurfaceSessionCommand>>,
        ) -> std::result::Result<
            tonic::Response<Self::SurfaceSessionStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the ContextSession method.
        type ContextSessionStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ContextSessionEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn context_session(
            &self,
            request: tonic::Request<tonic::Streaming<super::ContextSessionCommand>>,
        ) -> std::result::Result<
            tonic::Response<Self::ContextSessionStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct EngineServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EngineServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for EngineServiceServer<T>
    where
        T: EngineService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/allwright.engine.v1.EngineService/Ping" => {
                    #[allow(non_camel_case_types)]
                    struct PingSvc<T: EngineService>(pub Arc<T>);
                    impl<
                        T: EngineService,
                    > tonic::server::UnaryService<super::PingRequest> for PingSvc<T> {
                        type Response = super::PingResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PingRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EngineService>::ping(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/allwright.engine.v1.EngineService/SurfaceSession" => {
                    #[allow(non_camel_case_types)]
                    struct SurfaceSessionSvc<T: EngineService>(pub Arc<T>);
                    impl<
                        T: EngineService,
                    > tonic::server::StreamingService<super::SurfaceSessionCommand>
                    for SurfaceSessionSvc<T> {
                        type Response = super::SurfaceSessionEvent;
                        type ResponseStream = T::SurfaceSessionStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::SurfaceSessionCommand>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EngineService>::surface_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SurfaceSessionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/allwright.engine.v1.EngineService/ContextSession" => {
                    #[allow(non_camel_case_types)]
                    struct ContextSessionSvc<T: EngineService>(pub Arc<T>);
                    impl<
                        T: EngineService,
                    > tonic::server::StreamingService<super::ContextSessionCommand>
                    for ContextSessionSvc<T> {
                        type Response = super::ContextSessionEvent;
                        type ResponseStream = T::ContextSessionStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::ContextSessionCommand>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as EngineService>::context_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ContextSessionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EngineServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "allwright.engine.v1.EngineService";
    impl<T> tonic::server::NamedService for EngineServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
